name = "About"
uuid = "69d22d85-9f48-4c46-bbbe-7ad8341ff72a"
authors = ["TEC <git@tecosaur.net>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuliaSyntaxHighlighting = "dc6e5ff7-fb65-4e79-a425-ec3bc9c03011"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extensions]
PkgExt = "Pkg"

[compat]
InteractiveUtils = "1.11.0"
JuliaSyntaxHighlighting = "1.11.0"
Pkg = "1.11.0"
StyledStrings = "1.11.0"
